### ISSUE TITLE
Touch Not Working

### ISSUE THREAD

**Issue by toeachbyeach** [naruhaxor/AndroidKlipperScreen#12]
Tocuh not working on my S21 Samsung android. KlipperScreen is showing on it but the touch does not work. Running everything on Ubuntu.

I have seen a fix for a Pi for this issue which is editing a boot file but I don't have that file.

**Comment by naruhaxor** [comment]
so its not going to be the host hardware side it going to be app settings

HOWEVER i could be wrong look up (im at work rn) how to enable touchscreen on amd64 or I386 (aka x86 builds which are for desktop) Ubuntu and try that method see if that cures your issue because i have only tested piOS ARM64

Also could you please give me hardware specs OS ect?

Example:
Raspi5
piOS arm64 debian

**Comment by toeachbyeach** [comment]
I fixed it but I don'tk know how. I got it to the point where I had a mouse icon and then changed settings in xserver

**Comment by naruhaxor** [comment]
When you figure out how your fixed it you mind leaving a step by step for
other whom may also come across this issue

**Comment by toeachbyeach** [comment]
Sorry. I wasn't thinking. 

I followed this guide:  https://klipper.discourse.group/t/how-to-klipperscreen-on-android-smart-phones/1196/40

The fix I required was this:
"If you see a mouse cursor disable in xsdl config:
Device Configuration → In Mouse emulation → Mouse Emulation Mode → “Desktop no emulation”"

To bring up device configuration restart xsdl and before going into the blue screen it shows device configuration button at the top.
